version: "3.2"

services:
  kylin-data-proxy:
    container_name: kylin-data-proxy
    build:
      context: .
      dockerfile: Dockerfile
#    image: kylin-node:latest
    ports:
      - "8080:8080"
    env_file:
      - kylin-data-proxy.env
    environment:
      - KYLIN_ES_HOST=kylin-es:9200
    command: bash -c "/data_fetcher"
    depends_on:
      - init-es-index


  kylin-node:
    container_name: kylin-node
    build:
      context: .
      dockerfile: Dockerfile
#    image: kylin-node:latest
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
    command: bash -c "/kylin-node --dev --ws-external --rpc-external --rpc-methods Unsafe"
    depends_on:
      - kylin-data-proxy

  insert-ocw:
    container_name: insert-ocw
    build:
      context: .
      dockerfile: Dockerfile
    image: kylin-node:latest
    command: bash -c "sleep 30 && /insert_alice_key.sh"
    depends_on:
      - kylin-node

  kylin-market-frontend:
    container_name: kylin-market-frontend
    build:
      context: .
      dockerfile: Dockerfile
#    image: kylin-node:latest

    ports:
      - "3001:3001"
    command: bash -c "cd /apps && serve -p 3001 build"
    depends_on:
      - kylin-node

  kylin-es:
    container_name: kylin-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kylin-kibana:
    container_name: kylin-kibana
    ports:
      - "5601:5601"
    image: docker.elastic.co/kibana/kibana:7.8.1
    environment:
      ELASTICSEARCH_HOSTS: http://kylin-es:9200
    depends_on:
      - kylin-es

  init-es-index:
    container_name: init-es-index
#    image: kylin-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ES_HOST: http://kylin-es:9200
      ES_INDEX_NAME: kylin_access_tracking
      KIBANA_HOST: http://kylin-kibana:5601
    command: /bin/bash -c "sleep 60 && /init_es_index.sh"
    depends_on:
      - kylin-es
      - kylin-kibana

  init-kibana-dashboard:
    container_name: init-kibana-dashboard
#    image: kylin-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ES_HOST: http://kylin-es:9200
      ES_INDEX_NAME: kylin_access_tracking
      KIBANA_HOST: http://kylin-kibana:5601
    command: /bin/bash -c "sleep 120 && /init_kibana_dashboard.sh"
    depends_on:
      - kylin-es
      - kylin-kibana


volumes:
  es-data:
    driver: local

